spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  # 修正驱动类名（MySQL 8.x+）
    url: jdbc:mysql://localhost:3306/bms01?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai  # 修正 URL 格式
#    url: jdbc:mysql://localhost:3306/Library?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: mysql2023

mybatis:
    # 明确指定 Mapper 接口的包路径
    mapper-locations: classpath:src/main/resources/mapper/*.xml
    type-aliases-package: com.example.demo.model

#jwt:
#    secret: bookmanagesystem01

jwt:
  secret: "a3z6y9x2w5v8u1t4s7r0q3o6n9l2k5j8h1g4f7d0a3s6d9f2g5h8j1k4l7" # Base64编码后的密钥

server:
  port: 9000