spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  # 修正驱动类名（MySQL 8.x+）
    url: jdbc:mysql://localhost:3306/bms01?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai  # 修正 URL 格式
    username: root
    password: 123456

mybatis:
    # 明确指定 Mapper 接口的包路径
    mapper-locations: classpath:src/main/resources/mapper/*.xml
    type-aliases-package: com.example.demo.model

jwt:
    secret: bookmanagesystem01

server:
  port: 9000